server:
  port: 8080
spring:
  cloud: 
   gateway: 
    routes:
      - id: evento
        uri: lb://evento/
        predicates:
          - Path=/eventos/**
      - id: usuario
        uri: lb://usuario/
        predicates:
          - Path=/usuarios/**
      - id: pago
        uri: lb://pago/
        predicates:
          - Path=/pago/**
